# Generated by Django 4.2.18 on 2025-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
