# Generated by Django 4.2.18 on 2025-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_backend', '0002_user_custom_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
